
'''COSTANTS'''

#72 texts containing cities description of Milan municipality
text0 = "Rescaldina is a comune that is part of the Metropolitan City of Milan, in the Province of Milan in the Italian region Lombardy, with a population of 14,211 distributed over about 8 km and located about 25 kilometres northwest of Milan. Rescaldina borders the following municipalities: Cislago, Gorla Minore, Gerenzano, Marnate, Uboldo, Castellanza, Legnano and Cerro Maggiore. Except for Legnano and Cerro Maggiore, the other municipalities belong to the Province of Varese."
text1 = "Sesto San Giovanni, locally referred to as just Sesto, is a comune in the Metropolitan City of Milan, in the Italian region of Lombardy. It was awarded with the honorary title of città (city) by decree of 10 April 1954, signed by President Luigi Einaudi. An unimportant agglomerate of buildings until the 19th century, Sesto San Giovanni grew during the end of the 19th century and in the early 20th century, becoming the site of several industries, including companies such as Falck, Campari, Magneti Marelli and Breda. In that period the population increased rapidly, from 5,000 inhabitants in 1880 to 14,000 in 1911."
text2 = "Cinisello Balsamo is a comune of about 75,200 inhabitants in the Metropolitan City of Milan, in the Italian region of Lombardy, about 10 kilometres northeast of Milan city center. Cinisello Balsamo borders the following municipalities: Monza, Muggiò, Nova Milanese, Paderno Dugnano, Cusano Milanino, Sesto San Giovanni, Bresso. The current comune was formed in 1928 by the union of Cinisello and Balsamo, and received the honorary title of city through a presidential decree on 17 October 1972."
text3 = "Legnano is a town and comune municipality in the province of Milan, about 20 kilometres from central Milan. With 60,259, it is the thirteenth-most populous township in Lombardy. Legnano is located in the Alto Milanese and is crossed by the Olona River. The history of Legnano and its municipal area has been traced back to the 1st millennium BC via archaeological evidence. Already in remote times, in fact, the hills that line the Olona had proved to be habitable places. The town was established in 1261. Because of the historic victory of the Lombard League over Frederick Barbarossa at Legnano, it is the only town other than Rome named in the Italian national anthem. Every year the people of Legnano commemorate the battle with Palio di Legnano. In the institutional sphere, on 29 May, the date of the battle of Legnano, it was chosen as the regional holiday of Lombardy."
text4 = "Rho is a town and comune in the Metropolitan City of Milan in the Italian region of Lombardy, located about 14 kilometres northwest of Milan. The language spoken in Rho is Italian. Rho is lapped by the river Olona and crossed by its tributaries Bozzente and Lura, nowadays partially cloaked inside the town. At the north and east of the town, there is the road of national interest Strada statale 33 del Sempione, which in the past was crossing the town itself, in the current corso Europa. Rho is at the meeting point of railways linking Milan to Varese and Domodossola and Milan to Novara."
text5 = "Cologno Monzese is a comune in the Metropolitan City of Milan in the Italian region of Lombardy, located about 5 kilometres northeast of Milan. The population increased substantially after World War II, when many people from Southern Italy settled here. After being subject for a long time to the influence exerted by San Maurizio al Lambro Cologno received the honorary title of city with a presidential decree on September 19, 1996."
text6 = "Paderno Dugnano is a town and comune in the Metropolitan City of Milan, in Lombardy, northern Italy. It is bounded by comuni of Senago, Limbiate, Varedo, Cusano Milanino, Cormano, Nova Milanese, Bollate, Novate Milanese, Cinisello Balsamo. Paderno Dugnano is about 15 kilometers from the center of Milan. Following the unification of Italy in 1861, a reorganization of the internal subdivisions of the country ensued. By decree of 17 March 1869, the comuni of Paderno, Dugnano, Incirano, Cassina Amata, and Palazzolo Milanese were fused into a new comune called Paderno Milanese."
text7 = "Rozzano is a comune in the Metropolitan City of Milan, in the Italian region Lombardy, located about 9 kilometres south of Milan. Rozzano borders the following municipalities: Milan, Assago, Zibido San Giacomo, Opera, Pieve Emanuele, Basiglio. Rozzano received the honorary title of city with a presidential decree on July 21, 2003. The first government to officialise the birth of the municipality of Rozzano was that of Napoleon who in 1809 decreed the annexation of Torriggio and in 1811 those of Cassino Scanasio, Pontesesto and Quinto de' Stampi. The Austrians first annulled everything in 1816, but then reconsidered regarding Torriggio and Cassino Scanasio in 1841, while it was Vittorio Emanuele II in 1870 who sanctioned the final union with Pontesesto, which also brought Quinto as a dowry."
text8 = "San Giuliano Milanese is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located about 12 kilometres southeast of Milan. It received the honorary title of city with a presidential decree on April 24, 2000. The frazione of Viboldone is home to the historical Abbey of Viboldone. The town is served by the Borgolombardo and San Giuliano Milanese railway stations."
text9 = "Pioltello is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located about 7 kilometres northeast of Milan. Pioltello borders the following municipalities: Cernusco sul Naviglio, Vimodrone, Segrate, Rodano, Peschiera Borromeo, Vignate. Pioltello is served by Pioltello-Limito railway station. Among the churches, is the baroque-style, Roman Catholic Chiesa della Immacolata. Located about 6 kilometers east of Milan, the territory is between the SP ex SS 11 Padana Superiore and the SP 14 Rivoltana and is arranged along the north south axis, with an east west width of a couple of kilometers."
text10 = "Bollate is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located about 10 kilometres northwest of Milan. As of 30 November 2017, it had a population of 36,488. Bollate borders the following municipalities: Paderno Dugnano, Senago, Garbagnate Milanese, Arese, Cormano, Novate Milanese, Baranzate, Milan. Bollate received the honorary title of city, with a presidential decree on 11 October 1984. It is served by Bollate Centro railway station and Bollate Nord railway station. Sights include the historical Villa Arconati."
text11 = "Segrate is a town and comune located in the Metropolitan City of Milan in the Lombardy region of Northern Italy. An eastern suburb of Milan, in its area lies the airport of Milan Linate, the lake Idroscalo, the fair center of Novegro and the famous residential area Milano Due. Europark Idroscalo Milano is a popular amusement park that has been in existence since 1965. Although it is a small town, Segrate hosts large structures such as the CILEA Interuniversity Consortium, among the most advanced supercomputing centers in Europe, and the San Raffaele Hospital. Segrate received the honorary title of city with a presidential decree on 23 June 1989."
text12 = "Corsico is a comune in the Province of Milan in the Italian region Lombardy, bordering Milan on the southwest. Corsico received the honorary title of city with a presidential decree on 22 July 1987. Corsico is served by Corsico railway station."
text13 = "Cernusco sul Naviglio is a town and comune in the Metropolitan City of Milan, Lombardy, northwestern Italy. With a population of 33,436 as of 2015 it is the 14th-largest municipality in the metropolitan city. It is located 11 kilometres (6.8 mi) northeast of Milan along the Naviglio Martesana, which gives the town its name. The municipality of Cernusco sul Naviglio has a total area of 13.33 km2 with a median altitude of 133 metres above sea level."
text14 = "Abbiategrasso, formerly written Abbiate Grasso, is a comune and town in the Metropolitan City of Milan, Lombardy, northern Italy, situated in the Po valley approximately 22 kilometres from Milan and 38 kilometres from Pavia."
text15 = "San Donato Milanese is a comune in the Metropolitan City of Milan in the Italian region of Lombardy, located about 10 kilometres southeast of Milan. It is served by the San Donato underground station right on the borderline between the town and Milan and by the San Donato Milanese railway station, serving only trains for the Trenord S1 line 'Saronno–Lodi' and vice versa. Although the area was settled in ancient times, the origins of San Donato date back to the 7th century, when a pieve was founded here by the army of Grimoald I, Duke of Benevento. After a period under the Milanese family De Advocati, the town was a possession of the archbishops of Milan until the 16th century."
text16 = "Parabiago is a town located in the north-western part of the Metropolitan City of Milan, Lombardy, northern Italy. The town is crossed by the road to Sempione and Milan - Gallarate Railway; nearby flow the Olona river and the Canale Villoresi. Starting from the first Celtic-insubrian settlement, it developed during the Roman Empire rule, as documented by various archaeological discoveries of little objects, including the Parabiago Plate, a silver plate probably used to cover an ashes urn. "
text17 = "Buccinasco is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located about 7 kilometres southwest of Milan. The comune was created in 1841 through the merger of Buccinasco Castello, Rovido, Romano Banco and Gudo Gambaredo and, in 1871, Grancino and Ronchetto sul Naviglio. It remained an agricultural center until the 1950s. "
text18 = "Garbagnate Milanese is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located about 15 kilometre northwest of Milan. As of 30 November 2017, it had a population of 27.185. Garbagnate Milanese borders the following municipalities: Caronno Pertusella, Cesate, Lainate, Senago, Arese, Bollate, Baranzate. Garbagnate received the honorary title of city with a presidential decree on February 25, 1985."
text19 = "Bresso in the Metropolitan City of Milan in the Italian region Lombardy, located about 8 kilometres north of Milan. At the 2001 census the municipality had a population of 26,255 inhabitants and a population density of 8,027.2 persons/km², making it the most densely populated comune in Italy outside the Province of Naples. Bresso borders the following municipalities: Cinisello Balsamo, Cusano Milanino, Sesto San Giovanni, Cormano and Milan. Milan's general aviation airfield is located at Bresso and is the home of the Aero Club Milano and Aero Club Bresso."
text20 = "Lainate is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located about 15 kilometres northwest of Milan. Lainate borders the following municipalities: Caronno Pertusella, Origgio, Garbagnate Milanese, Nerviano, Arese, Rho, Pogliano Milanese. Lainate is home to Villa Visconti Borromeo Arese Litta, a Medici-inspired 1500s villa that today attracts many tourists because of its nymphaeum, and the headquarters of the confectionery company Perfetti Van Melle which sells candies and gums all over the world. It is also popular for Villoresi Canal and its forest, where people usually go for a walk or run."
text21 = "Magenta is a town and comune in the Metropolitan City of Milan in Lombardy, northern Italy. It became notable as the site of the Battle of Magenta in 1859. The color magenta takes its name from the battle. Magenta is the birthplace of Saint Gianna Beretta Molla and film producer Carlo Ponti The municipality of Magenta is part of the Parco naturale lombardo della Valle del Ticino, a Nature reserve included by UNESCO in the World Network of Biosphere Reserves."
text22 = "Cesano Boscone is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located about 6 kilometres southwest of Milan. Cesano Boscone borders the following municipalities: Milan, Corsico, Trezzano sul Naviglio. It is served by Cesano Boscone railway station."
text23 = "Peschiera Borromeo is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located about 12 kilometres southeast of Milan. It received the honorary title of city with a presidential decree on 6 August 1988. Peschiera Borromeo borders the following municipalities: Milan, Pioltello, Segrate, Rodano, Pantigliate, San Donato Milanese, Mediglia. The land was owned by the House of Borromeo of San Miniato in the 14th century and possibly earlier."
text24 = "Senago is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located about 13 kilometres north of Milan. As of 30 November 2017, it had a population of 21.519 and an area of 8.6 square kilometres. Senago borders the following municipalities: Limbiate, Cesate, Paderno Dugnano, Garbagnate Milanese, Bollate. The Villa San Carlo Borromeo is located in Senago. A historical residence, which was built in the XIV century, is immersed in a secular park of eleven hectares, 12 kilometres from Milan. It is the home town of Don Ambrogio Gianotti, a partigiano and the first priest of the church of St. Edward, Busto Arsizio"
text25 = "Trezzano sul Naviglio is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located about 9 km southwest of Milan. Trezzano sul Naviglio borders the municipalities of Buccinasco, Cusago, Cesano Boscone, Corsico, Gaggiano, Milan, and Zibido San Giacomo. It is served by Trezzano sul Naviglio railway station."
text26 = "Cornaredo is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located about 11 kilometres northwest of Milan. Cornaredo borders the following municipalities: Rho, Pregnana Milanese, Settimo Milanese, Bareggio, Cusago."
text27 = "Gorgonzola is a town in the Metropolitan City of Milan, Lombardy, northern Italy. It is part of the territory of the Martesana, north-east of Milan. Gorgonzola cheese is named after the town. The first written records mentioning the village of Gorgonzola date back to the 10th century: the notary clerk of the convent of Saint Ambrose in Milan was the caretaker of the church of Saints Gervasio and Protasio in 'Gorgontiola'."
text28 = "Cormano is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located about 9 kilometres north of Milan. Cormano borders the following municipalities: Paderno Dugnano, Bollate, Cusano Milanino, Bresso, Novate Milanese, Milan. It was previously served by the Cormano-Cusano Milanino railway station, which was closed in 2015, and replaced by the Cormano-Cusano Milanino railway station."
text29 = "Settimo Milanese is a comune in the Province of Milan in the Lombardy region of Italy. It is about 9 kilometres west of the city centre of Milan. The industrial district of Castelletto is home to Italtel and STMicroelectronics. Settimo Milanese borders Rho, Milan, Cornaredo, and Cusago. It's believed that the name comes from the distance between Settimo and Milan: it is in fact located near the seventh milestone of the road from Milan to Novara. The epithet 'Milanese' was added after the unification of Italy to distinguish it from other towns with the same name."
text30 = "Novate Milanese is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located about 8 kilometres northwest of Milan. Novate Milanese borders the following municipalities: Bollate, Baranzate, Cormano, Milan. Novate received the honorary title of city with a presidential decree on 16 January 2004. Novate Milanese had a station on the Milano-Saronno railway and it is served by S1 and S3 lines of Milan Transportation System."
text31 = "Arese is a comune in the Metropolitan City of Milan in the Italian region Lombardy, about 12 kilometres northwest of Milan. Arese borders the following municipalities: Lainate, Garbagnate Milanese, Bollate, Rho, Milan. Arese was awarded the honorary title of city by presidential decree of 25 October 1985. Of particular interest in the historical centre is the Church of St Peter and Paul."
text32 = "Cassano d'Adda is a town and comune in the Metropolitan City of Milan, Lombardy, Italy, located on the right side of the Adda River. It is on the border of the Metropolitan City of Milan and the province of Bergamo. It is served by Cassano d'Adda railway station. The territory of Cassano d'Adda is divided in two parts, which are both characterised by a difference in height of 20–25 meters, by the river Adda. The river, which still flows in a deep crack in Vaprio, stretches out in a wide riverbed in Cassano, in which its waters split into several branches separated by rocky and wooded islets."
text33 = "Cusano Milanino is a town and comune in the Metropolitan City of Milan, in Lombardy. Cusano Milanino is about 13 kilometers far from the centre of Milan. It borders Paderno Dugnano, Cinisello Balsamo, Cormano, and Bresso. The 18th-century Italian economist and antiquarian Count Carli died in the town, then part of the Duchy of Milan, in 1795. Cusano is also the birthplace of former football player and coach Giovanni Trapattoni."
text34 = "Melzo is a comune in the Province of Milan in the Italian region Lombardy, located about 20 kilometres east of Milan. As of 31 December 2004, it had a population of 18,400 and an area of 9.7 square kilometres. Melzo borders the following municipalities: Gorgonzola, Pozzuolo Martesana, Cassina de' Pecchi, Vignate, Truccazzano, Liscate. Melzo received the honorary title of city with a presidential decree on March 14, 1952. It is served by Melzo railway station."
text35 = "Corbetta is a comune in the Metropolitan City of Milan in the Italian region Lombardy. Corbetta is also home of the Sanctuary of the Madonna of Miracles where according to history, a miracle occurred in 1555, when Jesus emerged from a painting of the Infant and healed a local deaf child. The church became a destination for pilgrimages. The city of Corbetta has a planned layout, which is typical of the towns of the Po Valley, with forested areas and cultivations occupying roughly three-quarters of the municipality's territory."
text36 = "Melegnano is a comune and town in the Metropolitan City of Milan, Lombardy, northern Italy. The town lies 16 kilometres southeast of the city of Milan. It received the honorary title of city with a presidential decree on 26 August 1959. The town is served by the Melegnano railway station. Melegnano was a stronghold of Milan in the Italian Wars, and known particularly for the Battle of Marignano, a victory over the Swiss in 1515."
text37 = "Bareggio is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located gorgoabout 14 kilometres west of Milan. Bareggio borders the following municipalities: Pregnana Milanese, Cornaredo, Sedriano, Cusago, Cisliano."
text38 = "Nerviano is a comune in the northwestern part of the Metropolitan City of Milan in the Italian region Lombardy, located about 15 kilometres northwest of downtown Milan. Its territory is crossed by the Olona river and by the Villoresi Canal."
text39 = "Vimodrone is a comune in the Metropolitan City of Milan in the Italian region of Lombardy. It is located about 14 kilometres northeast of Milan. Vimodrone borders the following municipalities: Cologno Monzese, Cernusco sul Naviglio, Milan, Pioltello and Segrate. The area has historical associations with the Visconti di Modrone family."
text40 = "Pieve Emanuele is a comune in the Italian region of Lombardy, located about 13 kilometres south of Milan, and about 20 kilometres north of Pavia. Pieve Emanuele borders the following municipalities: Rozzano, Opera, Locate di Triulzi, Basiglio, Lacchiarella, Siziano. It is served by Pieve Emanuele railway station."
text41 = "Carugate is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located about 15 kilometres northeast of Milan. Carugate borders the following municipalities: Agrate Brianza, Caponago, Brugherio, Pessano con Bornago, Bussero, Cernusco sul Naviglio."
text42 = "Cerro Maggiore is a comune in the Province of Milan in the Italian region Lombardy, located about 20 kilometres northwest of Milan. On 25 August 1946 Benito Mussolini's corpse was hidden in the town, remaining here until 30 August 1957. The origin of the name derives from Latin cerrus which means cerro, a deciduous tree of the oak family. The adjective 'Maggiore' was inserted in 1862, to better identify the village by distinguishing it from the homonyms, putting them in emphasis is placed on the greater territorial and demographic extension."
text43 = "Cesate is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located about 17 kilometres northwest of Milan. Cesate borders the following municipalities: Limbiate, Solaro, Caronno Pertusella, Senago, Garbagnate Milanese. The origin of the flag comes from the noble Cixate family. During the Napoleonic era, the municipality was suppressed by a royal decree of 1809, and annexed to Garbagnate Milanese. Cesate regained its autonomy with the Austrian restoration."
text44 = "Solaro is a comune in the Metropolitan City of Milan in the Italian region Lombardy, located about 15 kilometres northwest of Milan. It has a population of about 14.000. Solaro borders the following municipalities: Saronno, Ceriano Laghetto, Bovisio-Masciago, Limbiate, Caronno Pertusella, Cesate."
text45 = "Rescaldina is a comune that is part of the Metropolitan City of Milan, in the Province of Milan in the Italian region Lombardy, with a population of 14,211 distributed over about 8 km2, and located about 25 kilometres northwest of Milan. Rescaldina borders the following municipalities: Cislago, Gorla Minore, Gerenzano, Marnate, Uboldo, Castellanza, Legnano and Cerro Maggiore. Except for Legnano and Cerro Maggiore, the other municipalities belong to the Province of Varese."
text46 = "Busto Garolfo is a comune in the Metropolitan City of Milan of 13 978 inhabitants. Busto Garolfo is located in the Italian region Lombardy, placed about 25 kilometres northwest of Milan. In the local dialect, belonging to Western Lombard, it is called Büst Picul ('Small Busto'), to distinguish it from Büsti Grandi ('Big Busto', which indicates the town of Busto Arsizio) and Büst Cava (or Büscaa, i.e. Buscate)."
text47 = "Opera is a comune (municipality) in the Metropolitan City of Milan in the Italian region Lombardy, located about 10 kilometres (6 mi) southeast of Milan. Opera borders the following municipalities: Locate di Triulzi, Milan, Pieve Emanuele, Rozzano, San Donato Milanese. It is home to the early 13th century Abbey of Mirasole."
text48 = "Cassina de' Pecchi is an Italian comune of 13,909 inhabitants in the metropolitan city of Milan in Lombardy . It is located along the Strada statale 11 Padana Superiore about 16 kilometres north-east from the centre of Milan. The municipality of Cassina de' Pecchi is part of the metropolitan city of Milan and the Martesana area . It borders Cernusco sul Naviglio to the west, Bussero to the north , Vignate to the south , Gorgonzola to the east and Melzo to the south-east. The territory is completely flat and crossed by the Martesana canal and is bordered to the east by the Molgora torrent. There are also numerous ditches and canals which, taking water from the canal , form an irrigation network that covers the entire territory."
text49 = "Canegrate is an Italian municipality of 12,713 inhabitants in the metropolitan city of Milan in Lombardy, approximately 25 kilometres from the capital. The same topic in detail: Geography of Lombardy and Legnanese (territory). Canegrate is located in the Legnano area , along the course of the Olona river , south of the Varese Prealps . The soil is mainly composed of pebbles, gravel , sand and clay. It was once covered by a thin layer of humus which was not very suitable for the growth of woods and subsequently for agricultural cultivation , so much so that it was largely groana . Due to the presence of clayey layers sedimented in correspondence with the ancient beds of the Olona, ​​the soil struggles to absorb rainwater."
text50 = "Trezzo sull'Adda is a comune (municipality) in the Metropolitan City of Milan in the Italian region Lombardy, located about 30 kilometres (19 mi) northeast of Milan on the Adda River. The Naviglio Martesana canal starts from the Adda in Trezzo's territory. Trezzo sull'Adda borders the following municipalities: Cornate d'Adda, Bottanuco, Capriate San Gervasio, Busnago, Grezzago, Vaprio d'Adda. Trezzo received the honorary title of city with a presidential decree on 8 July 2008."
text51 = "Sedriano is an Italian municipality of 12,999 inhabitants in the metropolitan city of Milan in Lombardy . It is part of the western hinterland of Milan and of the territory of Magentino . The municipal territory is between 135 and 151 m above sea level with an average altitude of 145 m above sea level. The overall altitudinal range is equal to 16 metres. Sedriano borders Vittuone to the west and south-west , Cisliano to the south , Bareggio to the east and north-east and finally Arluno , Vanzago and Pregnana Milanese to the north ."
text52 = "Baranzate, formerly a frazione of the neighboring comune of Bollate, is a comune (municipality) in the Metropolitan City of Milan, in the Italian region of Lombardy, about 8 kilometres (5 mi) northwest of Milan. It was created in 2004 after its previous establishment, in 2001, was declared unconstitutional. Baranzate is bordered by Bollate to the north and northwest, Novate Milanese to the east, and Milan's Roserio district to the south and southwest. Prior to 2001, Baranzate was a frazione of the comune of Bollate. It was established as a comune in its own right in November of that year by the promulgation of a regional law. In 2003 this law was declared unconstitutional by the Constitutional Court of Italy. The establishment of the new comune was annulled, and Barazate became once more a frazione of Bollate. In May 2004 a new regional law re-established the comune."
text53 = "Arluno also known as Manume is a comune (municipality) in the Metropolitan City of Milan in the Italian region Lombardy, located about 20 miles (32 km) west of Milan. Arluno borders the following municipalities: Parabiago, Nerviano, Pogliano Milanese, Casorezzo, Vanzago, Ossona, Sedriano, Santo Stefano Ticino, Vittuone, and Corbetta."
text54 = "Paullo is a comune (municipality) in the Metropolitan City of Milan in the Italian region Lombardy, located about 10 kilometres (6 mi) southeast of Milan. As of 30 April 2014, it had a population of 11,333 and an area of 8.9 square kilometres (3.4 sq mi). Paullo borders the following municipalities: Mediglia, Merlino, Mulazzano, Settala, Tribiano, Zelo Buon Persico. It received the honorary title of city with a presidential decree on April 2, 2009. A projected extension of Milan Metro line 3 to Paullo is currently on hold, awaiting funding."
text55 = "Castano Primo is a city and comune in Province of Milan, in the Italian region Lombardy, located about 35 kilometres (22 miles) northwest of Milan. Castano Primo borders the following municipalities: Lonate Pozzolo, Vanzaghello, Magnago, Nosate, Buscate, Cameri, Turbigo, Robecchetto con Induno, Cuggiono. It received the honorary title of city with a presidential decree on October 11, 1984. Castano was initially a Roman village that subsequently came under the Burgaria of Parabiago. It was converted to a military fortress by the Counts of Biandrate, passing eventually to the House of Visconti. During internal struggles within the House of Visconti, Castano was pillaged. The fortress was rebuilt in the 14th century and ownership passed to the Archbishop. Various periods of struggle and domination by the Visconti followed until, in 1447, Castano came under the control of the House of Sforza who gave it as fiefdom to a family favourite. In the 16th century the war between the French and Spanish waged around the town but remained it under the control of the Viscount of Brignano until 1717. By 1604 the population of Castano was around 1500 people."
text56 = "Pero in the Province of Milan in the Italian region Lombardy, located about 9 kilometres (6 mi) northwest of Milan. As of 31 December 2004, it had a population of 10,378 and an area of 5.0 square kilometres (1.9 sq mi). The municipality of Pero contains the frazioni (subdivisions, mainly villages and hamlets) Cerchiate and Cerchiarello. Pero borders the following municipalities: Rho, Milan. Pero is linked to Milan and Rho by the underground line M1 (a.k.a. 'red line')."
text57 = "Inzago in the Metropolitan City of Milan in the Italian region of Lombardy, located about 25 kilometres (16 mi) northeast of Milan. Inzago borders the following municipalities: Pozzo d'Adda, Masate, Gessate, Cassano d'Adda, Bellinzago Lombardo, Pozzuolo Martesana. The brothers Luca, Disma, Adolfo, and Polibio Fumagalli were all born in Inzago. All were composers; Adolfo, Luca, and Disma were pianists, and Polibio was an organist. Also born in Inzago were the supercentenarian Maria Redaelli, the architect Giuseppe Boretti, the Venerable Benigno Calvi, and the cyclist Gabriele Missaglia."
text58 = "Locate di Triulzi is a comune (municipality) in the Metropolitan City of Milan in the Italian region Lombardy, located about 14 kilometres (9 mi) southeast of Milan. Locate di Triulzi borders the following municipalities: San Donato Milanese, San Giuliano Milanese, Opera, Pieve Emanuele, Carpiano, Siziano. Sights include the 14th century Trivulzio Castle. It is served by Locate Triulzi railway station."
text59 = "Settàla is an Italian municipality of 7,381 inhabitants in the metropolitan city of Milan in Lombardy . Located in the Po Valley between the Adda and the Lambro , 15 kilometres east of the Lombard capital. The municipality is located 108 metres above sea level and has a surface area of ​​17.5 km². It also includes the hamlets of Caleppio (aggregated around 1753 ) and Premenugo (aggregated on 17 January 1869). Settala is included, albeit with some discrepancy, in the geographical area of ​​Martesana , which has undefined limits. The territory of Settala, although belonging to the Po Valley , is characterised by an imperceptible slope which makes the eastern part of the same lower in altitude; this characteristic meant that in the Middle Ages this part was lapped by the waters, or rather by the external marshes of the no longer existing Lake Gerundo , in the period of maximum expansion."
text60 = "Vignate is an Italian municipality of 9,373 inhabitants in the metropolitan city of Milan in Lombardy , today markedly industrial but historically of agricultural vocation. It is part of the Martesana territory. The name Vignate most likely derives from the toponym 'Vineate', from the Latin term vinea (' vineyard ') and the Celtic suffix –aite ('place', 'district'). The municipality has Roman origins, just look at the street layout of the historic center, and it owes its name to the typical cultivation of vines, once abundant in the municipal territory before the arrival of phylloxera . Vignate appears for the first time in a notarial deed dated 25 May 776. Upon the death of the last feudal lord, Count Antonio Teodoro Trivulzio, on 26 July 1678, the Vignanese Community paid the Spanish government 48 lire for each family for a total of 4,074 lire, thus obtaining two days later from the Spanish government of Milan the redemption from feudal constraints, unlike most of the other neighbouring lands which were then enfeoffed again."
text61 = "Magnano is a comune (municipality) in the Province of Biella in the Italian region Piedmont, located about 60 kilometres (37 mi) northeast of Turin and about 9 kilometres (6 mi) south of Biella. Magnano borders the following municipalities: Bollengo, Cerrione, Palazzo Canavese, Piverone, Torrazzo, Zimone, Zubiena. Musica Antica a Magnano is a non-profit association founded in 1986 to promote a festival offering an opportunity to hear historically informed performances of early music on original instruments. The Festival concerts are held in August and early September in either a 12th-century church San Secondo or in the town's 18th-century church. The latter also houses an organ built in 1794 by Giovanni Bruna and restored by Italo Marzi."
text62 = "Vanzago is a comune (municipality) in the Province of Milan in the Italian region Lombardy, located about 15 kilometres (9 mi) northwest of Milan. As of 31 December 2004, it had a population of 7,615 and an area of 6.2 square kilometres (2.4 sq mi). The municipality of Vanzago contains the frazioni (subdivisions, mainly villages and hamlets) Mantegazza, Valdarenne, and Tre Campane. Vanzago borders the following municipalities: Pogliano Milanese, Pregnana Milanese, Arluno, Sedriano."
text63 = "Gaggiano is a comune (municipality) in the Province of Milan in the Italian region Lombardy, located about 13 kilometres (8 miles) southwest of Milan. As of 31 December 2004, it had a population of 8,360 and an area of 26.7 square kilometres (10.3 sq mi). Gaggiano borders the following municipalities: Cusago, Cisliano, Albairate, Trezzano sul Naviglio, Vermezzo, Zibido San Giacomo, Gudo Visconti, Noviglio, Rosate. Gaggiano is served by Gaggiano railway station."
text64 = "Pessano con Bornago is an Italian municipality of 9,021 inhabitants in the metropolitan city of Milan in Lombardy. The municipality has an area of ​​6.66 square kilometers and is part of the Martesana territory. The name 'Pessano' is most likely of Gallo-Roman origin, perhaps from a landowner named Pettius or Pettianus. The Latin ending -anum denotes landed property, and is typical of towns of Roman origin. The toponym 'Bornago' seems to be more ancient, and may instead derive from an Insubrian village chief named Bornos (='the furious), with the addition of the typically Celtic ending -akon , indicating an inhabited place or more probably from the Celtic root bor- meaning 'source' in reference to the fountains. The stream that flows through the town, called Molgora , derives from the Celtic murg which means 'border river'. The locality Valera, which includes a farmhouse, is located west of the stream between the municipalities of Pessano con Bornago and Carugate . It seems that its name derives from the Latin vallis and it is likely that it indicated the construction of the small village in a flat area beyond the Molgora ."
text65 = "Vittuone is an Italian municipality of 9,287 inhabitants in the metropolitan city of Milan in Lombardy . It is part of the western hinterland of Milan and of the territory of Magentino. The municipal territory has an elongated shape and borders Corbetta to the west and south-west , Cisliano to the south , Sedriano to the east and north-east and finally Arluno to the north. Vittuone is about 20 kilometers west of the Lombard capital. The head of the Saretta fountain in Vittuone Morphologically, the territory of Vittuone is characterized by the flat environment typical of the Po Valley , mainly suitable for woods or crops. The altitude is between 135 and 151 m  above sea level. Generally, the lands of the municipality present homogeneous characteristics in their components."
text66 = "Assago is an Italian municipality of 9,326 inhabitants of the metropolitan city of Milan in Lombardy. Assago is located in the south-west of the metropolitan city of Milan and directly borders the capital. Important communication routes such as the A7 motorway and the western ring road pass through the municipal territory. It is bathed by the Naviglio Pavese and inside the South Milan Agricultural Park . In the area there is a dense network of canals that start from the canals or arise from springs in the ground. The altitude varies from 102 to111 m above sea level The entire municipality rests on a single geological entity from the Pleistocene consisting of sediments carried by rivers ( sand , gravel and silt )."
text67 = "Vaprio d'Adda ( Vàvar in local dialect and in Milanese dialect, Àer in Bergamo dialect and simply Vaprio until 1862) is an Italian municipality of 9,713 inhabitants in the metropolitan city of Milan in Lombardy. It is crossed by the Martesana canal and is included in the territory of the same name. The municipality is located halfway between Bergamo and Milan and is situated on the border between the two provinces, marked by the Adda river , on the Milanese side. Traces of its foundation have been lost. Some scholars believe that Vaprio d'Adda was originally founded as a castrum around the year 300 with the erection of the first bridge over the Adda River called 'Pons Aureoli', from the Roman general who had it built. In Roman times, the territory of Vaprio d'Adda was crossed by an important Roman road , the Via Gallica . We have to go back to 990 to find Vapris in a document. The toponym, however, could be of Celtic or Latin origin, linking the name to vadulum , meaning 'small ford'."
text68 = "Lacchiarella is an Italian municipality of 9,140 inhabitants in the metropolitan city of Milan in Lombardy, located south of the regional capital. The name Lacchiarella, in Lombard Laciarèla , means 'small dairy' and this definition must be attributed to the milk production of the area. The municipality of Lacchiarella is located south of Milan in the lower area of ​​the Po Valley . From Cascina Decima, the modern Lombard court of Lacchiarella, passed the Roman road that connected Mediolanum with Ticinum ( Pavia ). Its name derives from Ad Decimum , which recalls its distance in miles from Mediolanum."
text69 = "Gessate is an Italian municipality of 8,958 inhabitants in the metropolitan city of Milan in Lombardy. Agricultural and industrial center of the Lombard plain east of Milan (21 km), not far from the Adda river . The municipal territory is crossed to the north by the Villoresi canal , while the southern border is marked by the Naviglio . It is part of the Martesana territory . The extreme eastern part is included in the Rio Vallone supramunicipal park."
text70 = "Inveruno is an Italian municipality of 8,492 inhabitants of the metropolitan city of Milan in Lombardy with patron saint San Martino di Tours. Entrance sign to the municipality of Inveruno coming from Casorezzo The municipal territory has a horizontally elongated shape and borders Arconate and Busto Garolfo to the north , Casorezzo and Ossona to the east , Ossona and Mesero to the south and Cuggiono to the west . The municipality of Inveruno has a single hamlet, Furato . Morphologically, the territory of Inveruno is characterised by the flat environment typical of the Po Valley , mainly suitable for woods or crops. The altitude is around 161 m  above sea level."
text71 = "Bùssero is an Italian municipality of 8,369 inhabitants in the metropolitan city of Milan in Lombardy. The municipality, being bordered by the Martesana canal , is part of the territory of Martesana. The name of the settlement derives from boxwood , an evergreen shrub, which is also the origin of a widespread Lombard surname. The area was populated since Roman times and in 1906 a female sarcophagus from the period was found. Having appeared on the topographies of the plain east of Milan since 852 , about three centuries later Bussero gave its name to a prominent family, which in the Lombard capital founded the hospital of San Barnaba (with Goffredo da Bussero, relative and namesake of the more famous historian , in 1145 ) and of which Pagano, podestà in 1212 , was a member ."
text72 = "Pozzuolo Martesana is an Italian municipality of 8,796 inhabitants in the metropolitan city of Milan in Lombardy. It is part of the Martesana territory: one of the factories of the Ferrero confectionery group is located there. From an archaeological point of view, the oldest attestations in the territory of Pozzuolo Martesana are referable to a Roman tomb of the imperial age found in the hamlet of Bisentrate and to some burials of the Lombard era, datable to the first half of the 7th century , found in 2011 along the route of the BreBeMi motorway , south of the current town."


#list of texts to select randomly
allTexts = [text0, text1, text2, text3, text4, text5, text6, text7, text8, text9, text10, text11, text12, text13, text14, text15, text16, text17, text18, text19, text20, text21, text22, text23, text24, text25, text26, text27, text28, text29, text30, text31, text32, text33, text34, text35, text36, text37, text38, text39, text40, text41, text42, text43, text44, text45, text46, text47, text48, text49, text50, text51, text52, text53, text54, text55, text56, text57, text58, text59, text60, text61, text62, text63, text64, text65, text66, text67, text68, text69, text70, text71, text72]

# Color definitions
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

#Parameter setting
TEST_TIME = 10
LITTLE_CHAR = 30
BIG_CHAR = 45
LOW_SPEED = 0.8
HIGH_SPEED = 1.4
#Number of random value to generate per try
K = 8
